CREATE TABLE Players (
    Id UNIQUEIDENTIFIER NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Goals INT NOT NULL,
    TeamId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (Id),
    CONSTRAINT FK_Teams FOREIGN KEY (TeamId)
    REFERENCES Teams(Id)
);